# Generated by Django 5.0.1 on 2024-11-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['correo_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['id_descuento'], 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['id_direccion'], 'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['id_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reclamo',
            options={'ordering': ['id_reclamo'], 'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='descuento',
            table='Descuento',
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='Direccion',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='Pago',
        ),
        migrations.AlterModelTable(
            name='reclamo',
            table='Reclamo',
        ),
    ]
