# Generated by Django 5.0.1 on 2024-11-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_alter_cliente_options_alter_descuento_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descuento',
        ),
    ]
