# Generated by Django 5.1.3 on 2024-11-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_delete_descuento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password_cliente',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
