# Generated by Django 5.1.3 on 2024-11-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_alter_cliente_options_alter_cliente_password_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['correo_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
