# Generated by Django 5.1.3 on 2024-12-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_cliente_options_alter_cliente_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_direccion',
        ),
    ]
